# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MOVBo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MOVBo
pod 'AFNetworking'
pod 'FMDB'
pod 'Masonry'
pod 'NerdyUI'
pod 'SVProgressHUD'
pod 'Toast'
pod 'YYKit'
pod 'pop'
pod 'IQKeyboardManager'
pod 'MJRefresh'
pod 'KVOController'
pod 'ReactiveObjC'

end
